
apiVersion: v1
kind: Service
metadata:
  name: zigchain-service
spec:
  type: LoadBalancer
  selector:
    app: zigchain-node
  ports:
    - name: rpc
      port: 26657
      targetPort: 26657
    - name: p2p
      port: 26656
      targetPort: 26656
    - name: api
      port: 1317
      targetPort: 1317
